### ISSUE TITLE
Error when deploying multiple casified applications

### ISSUE THREAD

**Issue by sutrap** [soulwing/cas-extension#5]
I'm getting mltiple errors when i try to deploy multiple casified applications on Wildfly 8.2. 
It seems random which application fails.

``` java
12:09:51,951 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-15) MSC000001: Failed to start service jboss.deployment.unit."test.war".PARSE: org.jboss.msc.service.StartException in servic
e jboss.deployment.unit."test.war".PARSE: JBAS018733: Failed to process phase PARSE of deployment "test.war"
        at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:166) [wildfly-server-8.2.1.Final.jar:8.2.1.Final]
        at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948) [jboss-msc-1.2.2.Final.jar:1.2.2.Final]
        at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881) [jboss-msc-1.2.2.Final.jar:1.2.2.Final]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [rt.jar:1.8.0_45]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [rt.jar:1.8.0_45]
        at java.lang.Thread.run(Thread.java:745) [rt.jar:1.8.0_45]
Caused by: org.jboss.as.server.deployment.DeploymentUnitProcessingException: org.soulwing.cas.deployment.DescriptorParseException: ParseError at [row,col]:[4,4]
Message: expected identifier
        at org.soulwing.cas.deployment.DescriptorDeploymentProcessor.parseDescriptor(DescriptorDeploymentProcessor.java:99)
        at org.soulwing.cas.deployment.DescriptorDeploymentProcessor.deploy(DescriptorDeploymentProcessor.java:82)
        at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:159) [wildfly-server-8.2.1.Final.jar:8.2.1.Final]
        ... 5 more
Caused by: org.soulwing.cas.deployment.DescriptorParseException: ParseError at [row,col]:[4,4]
Message: expected identifier
        at org.soulwing.cas.deployment.XMLStreamDescriptorParser.parse(XMLStreamDescriptorParser.java:56)
        at org.soulwing.cas.deployment.DescriptorDeploymentProcessor.parseDescriptor(DescriptorDeploymentProcessor.java:95)
        ... 7 more
Caused by: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[4,4]
Message: expected identifier
        at org.soulwing.cas.deployment.ProfileReader.characters(ProfileReader.java:49)
        at org.soulwing.cas.deployment.XMLStreamDescriptorParser.parse(XMLStreamDescriptorParser.java:78)
        at org.soulwing.cas.deployment.XMLStreamDescriptorParser.parse(XMLStreamDescriptorParser.java:53)
        ... 8 more
```

**Comment by ceharris** [comment]
So if you deploy each of the individually, there's no problem?

**Comment by ceharris** [comment]
Would you please provide the contents of the cas.xml descriptor for test.war?

**Comment by sutrap** [comment]
just the standard:

<?xml version="1.0" encoding="UTF-8"?>
<cas xmlns="urn:soulwing.org:cas:1.0">
  <profile>cas-prod</profile>
  <add-api-dependencies/>
</cas>

It is funny though, each time it ist another application...

Each is a vaadin app where vaadin is packed as wildfly module...

**Comment by ceharris** [comment]
Weird.  What's really odd is that it seems unhappy with the cas.xml descriptor.

I'll try to reproduce, but I'm a bit stumped.

**Comment by sutrap** [comment]
By removing the <profile> tags and changing the configuration to default itseems to work ok so far...
